// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.2.3
// LVGL version: 8.3.4
// Project name: chat_gpt_new_gui

#include "app_sr.h"

#include "ui.h"
#include "app_ui_ctrl.h"
#include "esp_ota_ops.h"
#include "esp_system.h"
#include "esp_log.h"

static char *TAG = "ui-events";

// 设置按钮点击事件处理函数
void EventBtnSetupClick(lv_event_t *e)
{
    // 显示睡眠动画
    ui_sleep_show_animation();
}
// 睡眠面板点击事件处理函数
void EventPanelSleepClickCb(lv_event_t *e)
{
    // 启动一次语音识别
    app_sr_start_once();
    ESP_LOGI(TAG, "sr start once");
}

// 重启到出厂分区
static void RestartToFactoryPartition(void)
{
    const esp_partition_t *update_partition = esp_partition_find_first(ESP_PARTITION_TYPE_APP, ESP_PARTITION_SUBTYPE_APP_FACTORY, NULL);
    // 设置启动分区为出厂分区
    ESP_LOGI(TAG, "Switch to partition OTA_1");
    esp_ota_set_boot_partition(update_partition);
    esp_restart();
}

// WiFi重置确认点击事件处理函数
void EventWifiResetConfirmClick(lv_event_t *e)
{
    ESP_LOGI(TAG, "Reboot from WIFI Page to Factory Partition");
    RestartToFactoryPartition();
}

// 设置重置确认点击事件处理函数
void EventResetConfirm(lv_event_t *e)
{
    ESP_LOGI(TAG, "Reboot from Settings Page to Factory Partition");
    RestartToFactoryPartition();
}
